### ISSUE TITLE
What happens to (function (a, )).length?

### ISSUE THREAD

**Issue by atk** [jeffmo/es-trailing-function-commas#2]
Will it behave like a sparse array or should the parser just ignore the trailing comma? What about multiple missing arguments?

**Comment by chpio** [comment]
It's a simple change to the parser. why it should change anything about _.length_?

**Comment by atk** [comment]
The length of a function reflects the number of named arguments. Your answer suggests that you either haven't thought about it or originally intended that `(function(a, )).length === (function(a)).length;`

In any case, it is important that even proposed standards are complete and unambigious; otherwise their implementations might turn out different, leading to severe problems for developers.

**Comment by chpio** [comment]
> In any case, it is important that even proposed standards are complete and unambigious; otherwise their implementations might turn out different, leading to severe problems for developers.

:+1:

**Comment by benderTheCrime** [comment]
> In any case, it is important that even proposed standards are complete and unambigious; otherwise their implementations might turn out different, leading to severe problems for developers.

:+1:

**Comment by jeffmo** [comment]
I somehow missed this issue -- thanks for this, I will clarify.
Indeed the intent is that a trailing comma does not affect the length property

**Comment by jeffmo** [comment]
Clarified in https://github.com/jeffmo/es-trailing-function-commas/commit/0fab9b80d17d9593b9f57f36f6ff79f6cd74f1de
