### ISSUE TITLE
Why not just use leading commas, instead?

### ISSUE THREAD

**Issue by sterpe** [jeffmo/es-trailing-function-commas#5]
I.e.:

``` javascript
function foo (
  param1
  , param2
  , param3
) {
}
```

I feel like this style solves every major problem cited in the proposal related to vcs attribution and single line only modification without changing the existing specification in any way.

**Comment by jrencz** [comment]
you still have to modify 2 lines if you want to remove the first param or add one before: more or less the same as now without trailing commas where you have to modify line that held the last param if you want to add another.

**Comment by sterpe** [comment]
@jrencz, fair enough, but that's the only case.

**Comment by jrencz** [comment]
@sterpe another thing is that some people are allergic to "comma first" style. Main argument (which I happen to agree with) is that it's "purpose over readability".
Another thing is that it's a bit more common to add another param at the end to a function declaration than to add one at the beginning and here your suggestion covers more real-life use cases.

**Comment by sterpe** [comment]
Agreed, I'm just playjng devils advocate :)

**Comment by jrencz** [comment]
@sterpe in case of discussing suggested language features it's more than welcome
